version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
