version: "2"

run:
  timeout: 2m

linters:
  default: all
  disable:
    - cyclop
    - dupl
    - depguard
    - dogsled
    - exhaustruct
    - forcetypeassert  # Covered by revive linter's unchecked-type-assertion rule
    - funlen
    - gochecknoglobals
    - gosmopolitan
    - lll  # Covered by revive linter's line-length-limit rule
    - maintidx
    - mnd
    - noctx
    - nonamedreturns
    - paralleltest
    - prealloc  # Not recommended without performance profiling
    - testpackage
    - varnamelen
    - wrapcheck
    - noinlineerr
    - wsl # Deprecated since v2.2.0 and replaced by wsl_v5
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: '_test\.go'
        linters:
          - err113
          - goconst
  settings:
    ireturn:
      allow:
        # default values
        - anon
        - error
        - empty
        - stdlib
        # custom values
        # golang.org/x/crypto/ssh
        - Signer
        - PublicKey
    goheader:
      template: |-
        Copyright (c) Twingate Inc.
        SPDX-License-Identifier: MPL-2.0
    nestif:
      min-complexity: 7
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: unchecked-type-assertion
          exclude:
            - "TEST"
        - name: unused-parameter
          arguments:
            - allowRegex: "^_"
        - name: unused-receiver
          disabled: true
        - name: unhandled-error
          arguments:
            - "bytes.Buffer.Write"
    tagliatelle:
      case:
        extended-rules:
          yaml:
            case: goCamel
            initialism-overrides:
              CA: true

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/org/project) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule
