ARG GOLANG_VERSION=latest
ARG TARGETOS
ARG TARGETARCH

FROM --platform=$BUILDPLATFORM  golang:${GOLANG_VERSION} AS builder
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go install github.com/go-delve/delve/cmd/dlv@latest

FROM gcr.io/distroless/static-debian12:debug
ENTRYPOINT ["./dlv", "exec", "./gateway-debug", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--continue", "--", "start"]
COPY gateway-debug /
COPY LICENSE /
COPY --from=builder /go/bin/dlv /
