{
 "title": "Twingate Gateway",
 "description": "Grafana dashboard for Twingate Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Gateway HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total number of HTTP requests handled by the Gateway, grouped by request type, status code and request method.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code, method, type) (rate(twingate_gateway_http_requests_total[5m]))",
     "legendFormat": "{{type}} - {{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "description": "Number of currently active (in-progress) HTTP requests between Client and Gateway.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (twingate_gateway_http_active_requests{container=\"gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Percentile duration of HTTP requests between Client and Gateway, grouped by request type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(twingate_gateway_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(twingate_gateway_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, type) (rate(twingate_gateway_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=50"
    }
   ]
  },
  {
   "title": "Request Duration (Average)",
   "type": "timeseries",
   "description": "Average request durations between Client and Gateway, grouped by request type, status code and request method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(code, type, method) (rate(twingate_gateway_http_request_duration_seconds_sum[5m])) / sum by(code, type, method) (rate(twingate_gateway_http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{type}} - {{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Request Size (Percentile)",
   "type": "timeseries",
   "description": "Percentile size of HTTP requests by Client, grouped by request type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(twingate_gateway_http_request_size_bytes_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, type) (rate(twingate_gateway_http_request_size_bytes_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, type) (rate(twingate_gateway_http_request_size_bytes_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=50"
    }
   ]
  },
  {
   "title": "Request Size (Average)",
   "type": "timeseries",
   "description": "Average size of HTTP requests by Client, grouped by request type, status code and request method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(code, method, type) (rate(twingate_gateway_http_request_size_bytes_sum[5m])) / sum by(code, method, type) (rate(twingate_gateway_http_request_size_bytes_count[5m]))",
     "legendFormat": "{{type}} - {{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Response Size (Percentile)",
   "type": "timeseries",
   "description": "Percentile size of HTTP responses handled by Gateway, grouped by request type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(twingate_gateway_http_response_size_bytes_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, type) (rate(twingate_gateway_http_response_size_bytes_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, type) (rate(twingate_gateway_http_response_size_bytes_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=50"
    }
   ]
  },
  {
   "title": "Response Size (Average)",
   "type": "timeseries",
   "description": "Average size of HTTP response handled by Gateway, grouped by request type, status code and request method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(code, method, type) (rate(twingate_gateway_http_response_size_bytes_sum[5m])) / sum by(code, method, type) (rate(twingate_gateway_http_response_size_bytes_count[5m]))",
     "legendFormat": "{{type}} - {{method}} - {{code}}"
    }
   ]
  },
  { "title": "Kubernetes API Server Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total number of HTTP requests handled by the Kubernetes API Server, grouped by request type, method and status code.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code, method, type) (rate(twingate_gateway_api_server_requests_total[5m]))",
     "legendFormat": "{{type}} - {{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "description": "Number of currently active (in-progress) HTTP requests to Kubernetes API server.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (twingate_gateway_api_server_active_requests{container=\"gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (Percentile)",
   "type": "timeseries",
   "description": "Percentile duration of HTTP requests to Kubernetes API Server, grouped by request type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(twingate_gateway_api_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, type) (rate(twingate_gateway_api_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, type) (rate(twingate_gateway_api_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{type}}/quantile=50"
    }
   ]
  },
  {
   "title": "Request Duration (Average)",
   "type": "timeseries",
   "description": "Average request durations between Client and Gateway, grouped by request type, status code and request method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(code, type, method) (rate(twingate_gateway_api_server_request_duration_seconds_sum[5m])) / sum by(code, type, method) (rate(twingate_gateway_api_server_request_duration_seconds_count[5m]))",
     "legendFormat": "{{type}} - {{method}} - {{code}}"
    }
   ]
  },
  { "title": "Recorded Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Duration (Percentile)",
   "type": "timeseries",
   "description": "Percentile duration of the recorded session.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(twingate_gateway_recorded_session_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(twingate_gateway_recorded_session_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(twingate_gateway_recorded_session_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile=50"
    }
   ]
  },
  {
   "title": "Duration (Average)",
   "type": "timeseries",
   "description": "Average durations of the recorded session.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(twingate_gateway_recorded_session_duration_seconds_sum[5m])) / sum by(container) (rate(twingate_gateway_recorded_session_duration_seconds_count[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Connection",
   "type": "timeseries",
   "description": "Total number of Client TCP connections to Gateway, grouped by connection category.",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(connection_category) (rate(twingate_gateway_tcp_connections_total[5m]))",
     "legendFormat": "{{connection_category}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Number of currently active (in-progress) Client TCP connections to Gateway.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (twingate_gateway_active_tcp_connections{container=\"gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (Percentile)",
   "type": "timeseries",
   "description": "Percentile duration of Client TCP connections to Gateway, grouped by connection category.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, connection_category) (rate(twingate_gateway_tcp_connection_duration_seconds_bucket[5m])))",
     "legendFormat": "{{connection_category}}/quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, connection_category) (rate(twingate_gateway_tcp_connection_duration_seconds_bucket[5m])))",
     "legendFormat": "{{connection_category}}/quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le, connection_category) (rate(twingate_gateway_tcp_connection_duration_seconds_bucket[5m])))",
     "legendFormat": "{{connection_category}}/quantile=50"
    }
   ]
  },
  {
   "title": "Duration (Average)",
   "type": "timeseries",
   "description": "Average durations of Client TCP connections to Gateway, grouped by connection category.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(connection_category) (rate(twingate_gateway_tcp_connection_duration_seconds_sum[5m])) / sum by(connection_category) (rate(twingate_gateway_tcp_connection_duration_seconds_count[5m]))",
     "legendFormat": "{{connection_category}}"
    }
   ]
  },
  {
   "title": "Authentication via HTTP Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "Total Authentication",
   "type": "timeseries",
   "description": "Total number of HTTP Connect authentication attempts, grouped by status code.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(twingate_gateway_client_authentication_total[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Duration (Percentile)",
   "type": "timeseries",
   "description": "Percentile duration of HTTP Connect authentication attempts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(twingate_gateway_client_connection_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile=99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(twingate_gateway_client_connection_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile=95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(twingate_gateway_client_connection_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile=50"
    }
   ]
  },
  {
   "title": "Duration (Average)",
   "type": "timeseries",
   "description": "Average durations of HTTP Connect authentication attempts, grouped by status code.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(twingate_gateway_client_connection_duration_seconds_sum[5m])) / sum by(code) (rate(twingate_gateway_client_connection_duration_seconds_count[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}