{{/*
Expand the name of the chart.
*/}}
{{- define "gateway.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "gateway.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "gateway.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "gateway.labels" -}}
helm.sh/chart: {{ include "gateway.chart" . }}
{{ include "gateway.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "gateway.selectorLabels" -}}
app.kubernetes.io/name: {{ include "gateway.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "gateway.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "gateway.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Create the name of the TLS secret to use
*/}}
{{- define "gateway.tlsSecretName" -}}
{{- if .Values.tls.existingSecret }}
{{- .Values.tls.existingSecret }}
{{- else }}
{{- printf "%s-tls" (include "gateway.fullname" .) }}
{{- end }}
{{- end }}

{{/*
Get the alias of the resource
*/}}
{{- define "gateway.resourceAlias" -}}
{{- if and .Values.twingate.resource .Values.twingate.resource.enabled .Values.twingate.resource.extraAnnotations }}
{{- get .Values.twingate.resource.extraAnnotations "resource.twingate.com/alias" }}
{{- end }}
{{- end }}

{{/*
Create the alternative names hash of the TLS secret
*/}}
{{- define "gateway.alternativeNamesHash" -}}
{{- $resourceAlias := include "gateway.resourceAlias" . }}
{{- printf "%s-%s-%s" .Values.tls.ipAddresses .Values.tls.dnsNames $resourceAlias | sha256sum }}
{{- end }}

{{/*
Create the existing alternative names hash of the TLS secret
*/}}
{{- define "gateway.existingAlternativeNamesHash" -}}
{{- if .Values.tls.autoGenerated }}
{{- $secretName := include "gateway.tlsSecretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if and $existingSecret $existingSecret.metadata $existingSecret.metadata.annotations }}
{{- get $existingSecret.metadata.annotations "checksum/alternativeNames" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create the Twingate host
*/}}
{{- define "gateway.twingate.host" -}}
{{- default "twingate.com" .Values.twingate.host }}
{{- end }}


{{/*
Create the Certificate Authority singleton

Generate CA object and stored the singleton value in .Values._generatedCA.
Caller should use .Values._generatedCA after calling this template.
*/}}
{{- define "gateway.generateCA" -}}
{{- if not .Values._generatedCA }}
{{- $ca := genCA (printf "%s-ca" (include "gateway.fullname" .)) 365 }}
{{- $_ := set .Values "_generatedCA" $ca }}
{{- end }}
{{- end }}
