apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gateway.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.diagnosticMode.enabled }}
          image: "{{ .Values.image.repository }}:{{ .Values.diagnosticMode.image.tag }}"
          command: {{- toYaml .Values.diagnosticMode.command | nindent 12 }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          args:
            - "start"
            - "--network"
            - {{ .Values.twingate.network }}
            - "--host"
            - {{ include "gateway.twingate.host" . }}
          ports:
            - name: https
              containerPort: {{ (.Values.containerPorts | default dict).https | default 8443 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: https
              scheme: HTTPS
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: {{ ternary 3600 1 .Values.diagnosticMode.enabled }}
          readinessProbe:
            httpGet:
              port: https
              scheme: HTTPS
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: {{ ternary 3600 1 .Values.diagnosticMode.enabled }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tls-secret-volume
              mountPath: /etc/tls-secret-volume
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tls-secret-volume
          secret:
            secretName: {{ include "gateway.tlsSecretName" . }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
