apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.twingate.resource.enabled }}
    resource.twingate.com: "true"
    resource.twingate.com/type: "Kubernetes"
    resource.twingate.com/tlsSecret: {{ include "gateway.tlsSecretName" . }}
    {{- with .Values.twingate.resource.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
