{{- if and .Values.ssh.enabled .Values.ssh.ca .Values.ssh.ca.vault .Values.ssh.ca.vault.auth .Values.ssh.ca.vault.auth.appRole (not .Values.ssh.ca.vault.auth.appRole.existingSecretIdSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.sshVaultAppRoleSecretIdSecretName" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  secretId: {{ required "ssh.ca.vault.auth.appRole.secretId is required" .Values.ssh.ca.vault.auth.appRole.secretId | b64enc }}
{{- end }}
