name: Release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  packages: write

env:
  GOLANG_VERSION: 1.26.2

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.19.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Create Buildx builder
        run: |
          docker buildx create \
            --name twingate-gateway-builder \
            --driver docker-container \
            --use

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_REGISTRY: ghcr.io/twingate
          DOCKER_BUILDX_BUILDER: twingate-gateway-builder

      - name: Helm Publish (Github)
        env:
          REGISTRY: ghcr.io
        run: |
          CURRENT_VERSION=$(go tool svu current)
          CHART_VERSION="${CURRENT_VERSION:1}"
          echo "🚀 Publishing helm chart version $CHART_VERSION"
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u twingate --password-stdin $REGISTRY
          helm package deploy/gateway --version $CHART_VERSION --app-version $CHART_VERSION
          helm push gateway-$CHART_VERSION.tgz oci://$REGISTRY/twingate/helmcharts
